dist: trusty
language: r
r: bioc-release
cache: packages

os:
  - osx
  - linux

r_packages:
  - nlme

bioc_packages:
  - QUBICdata

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq update                                  ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y tcl8.5 tcl8.5-dev tk8.5 tk8.5-dev; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]  ; then sudo tlmgr install framed titling                        ; fi